# docker swarm 部署mongodb replica set
version: '3.7'
services:
  mongo:
    image: zyhcool/mongo:replSet
    ports:
      - 27017:27017
    volumes:
      - /data/db
      - /var/projects/mongo-image:/etc/mongo
    networks:
      - swarm-net
    deploy:
      mode: replicated
      replicas: 4
networks:
  swarm-net:
    driver: overlay
