# docker swarm 部署
version: '3.7'
services:
  mongo:
    image: zyhcool/mongo:replSet
    ports:
      - 0.0.0.0:27017:27017/tcp
    volumes:
      - ~/data/db:/data/db
      - /var/projects/mongo-image:/etc/mongo
    networks:
      - swarm-net
    deploy:
      mode: replicated
      replicas: 2
networks:
  swarm-net:
    driver: overlay
